MylunesChampions.G["enUS"] = {

COMPANION = "companion",
PET = "pet",
POSSESSIVE = "'s",

-- from LibBabble-CreatureType-3.0
CREATURE_TYPES = {
	Bat = "Bat",
	Bear = "Bear",
	Beast = "Beast",
	Beetle = "Beetle",
	["Bird of Prey"] = "Bird of Prey",
	Boar = "Boar",
	["Carrion Bird"] = "Carrion Bird",
	Cat = "Cat",
	Chimaera = "Chimaera",
	["Core Hound"] = "Core Hound",
	Crab = "Crab",
	Critter = "Critter",
	Crocolisk = "Crocolisk",
	Demon = "Demon",
	Devilsaur = "Devilsaur",
	Dog = "Dog",
	Doomguard = "Doomguard",
	Dragonhawk = "Dragonhawk",
	Dragonkin = "Dragonkin",
	Elemental = "Elemental",
	Felguard = "Felguard",
	Felhunter = "Felhunter",
	Fox = "Fox",
	["Gas Cloud"] = "Gas Cloud",
	Ghoul = "Ghoul",
	Giant = "Giant",
	Gorilla = "Gorilla",
	Humanoid = "Humanoid",
	Hyena = "Hyena",
	Imp = "Imp",
	Mechanical = "Mechanical",
	Monkey = "Monkey",
	Moth = "Moth",
	["Nether Ray"] = "Nether Ray",
	["Non-combat Pet"] = "Non-combat Pet",
	["Not specified"] = "Not specified",
	Raptor = "Raptor",
	Ravager = "Ravager",
	["Remote Control"] = "Remote Control",
	Rhino = "Rhino",
	Scorpid = "Scorpid",
	Serpent = "Serpent",
	["Shale Spider"] = "Shale Spider",
	Silithid = "Silithid",
	Spider = "Spider",
	["Spirit Beast"] = "Spirit Beast",
	Sporebat = "Sporebat",
	Succubus = "Succubus",
	Tallstrider = "Tallstrider",
	Totem = "Totem",
	Turtle = "Turtle",
	Undead = "Undead",
	Voidwalker = "Voidwalker",
	["Warp Stalker"] = "Warp Stalker",
	Wasp = "Wasp",
	["Water Elemental"] = "Water Elemental",
	["Wind Serpent"] = "Wind Serpent",
	Wolf = "Wolf",
	Worm = "Worm",
},

EMOTE_BYE = {
	pattern_someoneAtTarget = "%s waves goodbye to %t.  Farewell!",
	pattern_someoneAtYou = "%s waves goodbye to you.  Farewell!",
	pattern_someoneNoTarget = "%s waves goodbye.  Farewell!",
},
EMOTE_CHEER = {
	pattern_someoneAtTarget = "%s cheers at %t!",
	pattern_someoneAtYou = "%s cheers at you!",
	pattern_someoneNoTarget = "%s cheers.",
},
EMOTE_GREET = {
	pattern_someoneAtTarget = "%s greets %t with a hearty hello!",
	pattern_someoneAtYou = "%s greets you with a hearty hello!",
	pattern_someoneNoTarget = "%s greets everyone warmly.",
},
EMOTE_STARE = {
	pattern_someoneAtTarget = "%s stares %t down.",
	pattern_someoneAtYou = "%s stares you down.",
	pattern_someoneNoTarget = "%s stares off into the distance.",
},
EMOTE_WAVE = {
	pattern_someoneAtTarget = "%s waves at %t.",
	pattern_someoneAtYou = "%s waves at you.",
	pattern_someoneNoTarget = "%s waves.",
},

}
